config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :communities
  resources :community_joins, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following
    end
  end

  resources :communities do
    member do
      get :followers
    end
  end
  



  # resources :communities, only: [:create, :destroy]
  # resources :communities, only: [:index, :show, :create, :destroy]
  
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :community, dependent: :destroy
  has_many :community_join, dependent: :destroy
  has_many :following, through: :community_join, source: :community

  # cookiesの保存場所
  attr_accessor :remember_token
  
  # ActiveRecordのコールバックメソッド（before_save > DBに保存する前に呼ばれる）
  # before_save { self.email = email.downcase }
  before_save { email.downcase! }   #破壊的メソッド

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGE_ = /\A[\w+\-.]+@[a-z\d\-.]+               \.[a-z]+\z/i
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\- ]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
              format: { with: VALID_EMAIL_REGEX },
              uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  ### クラスメソッド群 ###

  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # 試作feedの定義
  def feed
    Community.where("user_id = ?", id)
  end

  # コミュニティをフォローする
  def follow(community)
    following << community
  end

  # コミュニティをフォロー解除する
  def unfollow(community)
    # debugger
    CommunityJoin.find_by(community_id: community.id).destroy
  end

  # 現在のコミュニティがフォローしてたらtrueを返す
  def following?(community)
    following.include?(community)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # ログイン済みかどうかを事前にチェック
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following]
  # ユーザー編集ページは自分自身以外は入れないようにチェック
  before_action :correct_user,   only: [:edit, :update]
  # 管理者だけがdestroyアクションを発動してユーザーを削除できる
  before_action :admin_user,     only: :destroy

  def index
    @users = User.paginate(page: params[:page])
    # @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @communities = @user.community
    @followes = @user.following
    # 現在のURLを記憶
    before_location user_path
    # @communities = @user.community.paginate(page: params[:page], per_page: 5)
    # @followes = @user.following.paginate(page: params[:page], per_page: 5)
    # debugger
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    # @user = User.find(params[:id])
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile update"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @communities = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    # beforeアクション

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
  
end

app/helpers/users_helper.rb
module UsersHelper

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<!-- form_for(モデルオブジェクト, url: フォームの送信先) -->
<!-- フォームの送信先とは、action=""の中身に設定するURLのこと -->


<!-- form_withを使うと送信先を自動で判別されて、エラー時には/usersのルーティングで処理されてしまい、結果エラー表示されなくなる -->
<%= form_for(@user, url: yield(:url)) do |f| %>

  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
      
      <!-- ユーザーが管理者権限を有するか？ && ユーザーがログイン済みか？ -->
      <% if current_user.admin? && !current_user?(user) %>
    |   <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
      <% end %>

    </li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<% provide(:url, user_path) %>
<% provide(:button_text, "Save changes") %>

<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank" rel="noopener">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <!-- userデータをリストとして認識し、userパーシャルを呼び出す -->
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:url, signup_path) %>
<% provide(:button_text, 'Create my account')%>

<h1>Sign up</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= render 'form' %>
    
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="user-show">

    <!-- 左カラム -->
    <aside class="col-md-2">

      <!-- ユーザー情報 -->
      <section>
      <div class="center side-icon">
        <%= link_to gravatar_for(@user, size: 128), @user %>
      </div>
      </section>

      <div class="center">
        <span class="side-user">
          <%= link_to @user.name, @user %>
        </span>
      </div>

      <!-- コミュニティ作成ボタン -->
      <% if current_user?(@user) %>
        <div class="side-btn">
          <%= link_to "コミュニティ作成", new_community_path, class: "btn btn-sm btn-primary btn-block" %>
        </div>
      <% end %>

    </aside>

    <!-- 右カラム -->
    <div class="col-md-10">

      <!-- マイコミュニティ／参加コミュニティ 選択タブ -->
      <div class="tab">
        <ul class="nav nav-tabs" role="tablist">
          <li class="active" role="presentation">
            <a aria-controls="tab_a" data-toggle="tab" href="#tab_a" role="tab"> MyList </a>
          </li>
          <li role="presentation">
            <a aria-controls="tab_b" data-toggle="tab" href="#tab_b" role="tab"> Follow </a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="tab_a" role="tabpanel">
            <p class="tab-head">
              作成コミュニティ
            </p>

            <!-- 作成コミュニティ -->
            <div class="scroll-box">
              <% if @user.community.any? %>
                <ol class="user-show">
                  <%= render @communities %>
                </ol>
              <% end %>
            </div>
          </div>
          <div class="tab-pane" id="tab_b" role="tabpanel">
            <p class="tab-head">
              参加コミュニティ
            </p>

            <!-- 参加コミュニティ -->
            <div class="scroll-box">
              <% if @followes.any? %>
                <ol class="user-show">
                  <%= render @followes %>
                </ol>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>

</div>



<%
=begin
%>

<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <!-- Community情報 -->
  <div class="col-md-8">
    <% if @user.community.any? %>
      <h3>Communities (<%= @user.community.count %>)</h3>
        <ol class="communities">
          <%= render @communities %>
        </ol>
      <%= will_paginate @communities %>
    <% end %>
  </div>
</div>

    <h3>Communities (<%= @user.community.count %>)</h3>
            <div class="center"><%= will_paginate @communities %></div>

<%
=end
%>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Communities:</b> <%= @user.communities.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @communities %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>