config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'

  # get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :communities
  resources :community_joins, only: [:create, :destroy]
  
  resources :users do
    member do
      get :following
    end
  end

  resources :communities do
    member do
      get :followers
    end
  end
  



  # resources :communities, only: [:create, :destroy]
  # resources :communities, only: [:index, :show, :create, :destroy]
  
  # get 'static_pages/home'
  # get 'static_pages/help'
  # get 'static_pages/about'
  # get 'static_pages/contact'
  
end

app/models/community.rb
class Community < ApplicationRecord

  #User／Communityの関連付け（１対１）
  belongs_to :user
  has_many :community_join, dependent: :destroy
  has_many :followers, through: :community_join, source: :user
  
  #デフォルトの順序を指定
  default_scope -> { order(created_at: :desc) }
  
  #画像アップローダー
  mount_uploader :picture, PictureUploader
  validate :picture_size
  
  #バリデーション
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :body, presence: true, length: { maximum: 1000 }
  validates :tag, allow_blank: true, length: { maximum: 10 }


  private
  
    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  before_action :logged_in_user, only: [:create, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update, :destroy]

  def index
    @communities = Community.paginate(page: params[:page])
    #現在のURLを記憶
    before_location communities_path
  end

  def new
    @community = Community.new
    @user = current_user if logged_in?
  end

  def show
    @community = Community.find(params[:id])
    @user = current_user if logged_in?
  end

  def edit
    # @community = Community.find(params[:id])
    @user = current_user if logged_in?
  end

  def create
    @community = current_user.community.build(community_params)
    @user = current_user if logged_in?
    if @community.save
      flash[:success] = "Community created!"
      redirect_to @community
    else
      @feed_items = []
      render 'new'
    end
  end

  def update
    @user = current_user if logged_in? 
    if @community.update_attributes(community_params)
      flash[:success] = "Community updated"
      redirect_to @community
    else
      render 'edit'
    end
  end
  
  def destroy
    @community.destroy
    flash[:success] = "Community deleted"
    # redirect_to request.referrer || root_url
    redirect_to redirect_before_url
  end
  
  private

    def community_params
      params.require(:community).permit(:title, :body, :tag, :picture)
    end

    def correct_user
      @community = current_user.community.find_by(id: params[:id])
      redirect_to root_url if @community.nil?
    end

end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_community.html.erb
<li id="community-<%= community.id %>">

  <!-- Communityヘッダ部分 -->
  <div class="community_header">
    <!-- タグ -->
    <span class="col-md-7">
      <% unless community.tag == "" %>
        <span class="tag"><%= community.tag %></span>
      <% end %>
    </span>

    <!-- ユーザー名 -->
    <span class="col-md-3">
      <span class="user-name">
        <%= link_to gravatar_for(community.user, size: 24), community.user %>
        <%= link_to community.user.name.truncate(18), community.user %>
      </span>
    </span>

    <!-- 更新日 -->
    <span class="col-md-2">
      <span class="time-stamp">公開日: <%= community.updated_at %></span>
    </span>
  </div>


  <!-- Communityタイトル （32文字以上は...と省略させる）-->
  <div class="community_title">
    <%= link_to community.title.truncate(32), community%>
  </div>


  <!-- Communityボディ -->
  <div>
    <!-- 本文（64文字以上は...と省略させる）-->
    <span class="col-md-10">
      <span class="community_body"><%= community.body.truncate(52) %></span>
    </span>

    <!-- フォロワー人数 -->
    <span class="col-md-2">
      <span class="follower">参加者: <%= community.followers.count %>人</span>
    </span>
  </div>
  
</li>

app/views/communities/_follow.html.erb
<%= form_for(current_user.community_join.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :community_id, @community.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/communities/_follow_form.html.erb
<% unless current_user?(@community.user) %>
  <div id="follow_form">
  <% if current_user.following?(@community) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/communities/_unfollow.html.erb
<%= form_for(current_user.community_join.find_by(community_id: @community.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-default" %>
<% end %>

app/views/communities/edit.html.erb
<% provide(:title, "Edit community") %>


<ul class="community-edit">

  <!-- 操作ボタン（左サイドバー） -->
  <div class="side-leftbar">

    <!-- ユーザー情報 -->
    <% if logged_in? %>
      <section>
      <div class="center side-icon">
          <%= link_to gravatar_for(@user, size: 96), @user %>
      </div>
      </section>

      <div class="center">
        <span class="side-user">
            <%= link_to @user.name, @user %>
        </span>
      </div>
    <% end %>

    <!--戻るボタン-->
    <div class="side-btn">
      <%= link_to "戻る", @community, class: "btn btn-sm btn-primary btn-block" %>
    </div>

  </div>

  <!-- コミュニティー詳細のメインブロック -->
  <div class="main">

    <!-- 入力フォーム -->
    <%= form_for(@community) do |f| %>

      <%= render 'shared/error_messages', object: f.object%>

      <div class="form-block">
        <%= f.label "タグ" %>
        <%= f.text_field :tag, class: 'form-control' %>
        <p>*10字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "タイトル" %>
        <%= f.text_field :title, class: 'form-control' %>
        <p>*30字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "内容" %>
        <%= f.text_area :body, size: "200x12", class: 'form-control' %>
        <p>*1000字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "添付画像" %>
        <p><%= image_tag @community.picture.url if @community.picture? %></p>
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
      </div>

      <div class="form-block">
        <%= f.submit "更 新", class: "btn btn-primary" %>
      </div>

    <% end %>

    </div>
  </div>
</ul>






<%
=begin
%>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <!-- 戻るボタン -->
    <%= link_to "戻る", @community, class: "btn btn-sm btn-primary" %>
    
    <h1>Update your community</h1>
    
    <%= form_for(@community) do |f| %>
      <%= render 'shared/error_messages', object: f.object%>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
      <%= f.label :body %>
      <%= f.text_field :body, class: 'form-control' %>
      <%= f.label :picture %>
      <p><%= image_tag @community.picture.url if @community.picture? %></p>
      <span class="picture">
        <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
      </span>
      <%= f.submit "Update changes", class: "btn btn-primary" %>
    <% end %>
    
    <div class="gravatar_edit">
      <%= gravatar_for @community.user %>
      <p><%= @community.user.name %></p>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
    
  </div>
</div>


<%
=end
%>

app/views/communities/index.html.erb
<% provide(:title, 'All Community') %>

<h1>All Community</h1>

<%= will_paginate @communities %>
<ul class="communities">
    <%= render @communities %>
</ul>
<%= will_paginate @communities %>

app/views/communities/new.html.erb
<% provide(:title, "New community") %>


<ul class="community-edit">

  <!-- 操作ボタン（左サイドバー） -->
  <div class="side-leftbar">

    <!-- ユーザー情報 -->
    <% if logged_in? %>
      <section>
      <div class="center side-icon">
          <%= link_to gravatar_for(@user, size: 96), @user %>
      </div>
      </section>

      <div class="center">
        <span class="side-user">
            <%= link_to @user.name, @user %>
        </span>
      </div>
    <% end %>

    <!--戻るボタン-->
    <div class="side-btn">
      <%= link_to "戻る", @user, class: "btn btn-sm btn-primary btn-block" %>
    </div>

  </div>

  <!-- コミュニティー詳細のメインブロック -->
  <div class="main">

    <!-- 入力フォーム -->
    <%= form_for(@community) do |f| %>

      <%= render 'shared/error_messages', object: f.object%>
      <div class="form-block">
        <%= f.label "タグ" %>
        <%= f.text_field :tag, class: 'form-control' %>
        <p>*10字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "タイトル" %>
        <%= f.text_field :title, class: 'form-control' %>
        <p>*30字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "内容" %>
        <%= f.text_area :body, size: "200x12", class: 'form-control' %>
        <p>*1000字以内</p>
      </div>

      <div class="form-block">
        <%= f.label "添付画像" %>
        <p><%= image_tag @community.picture.url if @community.picture? %></p>
        <span class="picture">
          <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
        </span>
      </div>

      <div class="form-block">
        <%= f.submit "登 録", class: "btn btn-primary" %>
      </div>

    <% end %>

    </div>
  </div>
</ul>

app/views/communities/show.html.erb
<ul class="community-show">

  <!-- 操作ボタン（左サイドバー） -->
  <div class="side-leftbar">

    <!-- ユーザー情報 -->
    <% if logged_in? %>
      <section>
      <div class="center side-icon">
          <%= link_to gravatar_for(@user, size: 96), @user %>
      </div>
      </section>

      <div class="center">
        <span class="side-user">
            <%= link_to @user.name, @user %>
        </span>
      </div>
    <% end %>


    <!--戻るボタン-->
    <div class="side-btn"><%= link_to "戻 る", redirect_before_url, class: "btn btn-sm btn-primary btn-block" %></div>

    <!-- 編集ボタン -->
    <% if current_user?(@community.user) %>
      <div class="side-btn"><%= link_to "編 集", edit_community_path(@community), class: "btn btn-sm btn-primary btn-block" %></div>
      <div class="side-btn"><%= link_to "削 除", @community, class: "btn btn-sm btn-primary btn-block", method: :delete, data: { confirm: "You sure?" } %></div>
    <% end %>
  </div>

  <!-- 参加ユーザー（フォロー）一覧を表示（右サイドバー） -->
  <div class="side-rightbar">

    <!-- フォローボタン -->
    <div class="follow-btn">
      <%= render 'follow_form' if logged_in? %>
    </div>

    <div class="side-header">参加者: <span id="followers"><%= @community.followers.count %></span>人</div>

    <div id="followers-list">
      <% @community.followers.each do |follower| %>
        <p>
          <span class="side-user">
            <%= link_to gravatar_for(follower, size: 24), follower %>
            <%= link_to follower.name.truncate(18), follower %>
          </span>
        </p>
      <% end %>
    </div>

  </div>

  <!-- コミュニティー詳細のメインブロック -->
  <div class="main">

    <li id="community-<%= @community.id %>">

      <!-- Communityヘッダ部分 -->
      <div class="community_header">
        
        <!-- タグ -->
        <span class="col-md-7">
          <% unless @community.tag == "" %>
            <span class="tag"><%= @community.tag %></span>
          <% end %>
        </span>
        

        <!-- ユーザー名 -->
        <span class="col-md-3">
          <span class="user-name">
            <%= link_to gravatar_for(@community.user, size: 24), @community.user %>
            <%= link_to @community.user.name.truncate(18), @community.user %>
          </span>
        </span>

        <!-- 更新日 -->
        <span class="col-md-2">
          <span class="time-stamp">公開日: <%= @community.updated_at %></span>
        </span>
      </div>

      <!-- Communityタイトル （32文字以上は...と省略させる）-->
      <div class="community_title">
        <%= @community.title.truncate(32) %>
      </div>

      <!-- アップロードPicture -->
      <%= image_tag @community.picture.url if @community.picture? %>


      <!-- Communityボディ -->
      <div class="community_body">
          <%= @community.body %>
      </div>

    </div>
  </div>
</ul>




<% 
=begin
%>
    <!-- ユーザー画像 -->
    <%= link_to gravatar_for(@community.user, size: 50), @community.user %>

    <!-- ユーザー名 -->
    <span class="user"><%= link_to @community.user.name, @community.user %></span>

    <!-- Communityタイトル -->
    <span class="community_title"><%= @community.title %></span>

    <!-- Communityボディ -->
    <span class="community_body">
      <%= @community.body %>
      <!-- アップロードPicture -->
      <%= image_tag @community.picture.url if @community.picture? %>
    </span>

    <!-- 編集ボタン -->
    <% if current_user?(@community.user) %>
      <%= link_to "編集", edit_community_path(@community), class: "btn btn-sm btn-primary" %>
      <%= link_to "削除", @community, class: "btn btn-sm btn-primary", method: :delete, data: { confirm: "You sure?" } %>
    <% end %>

    <!--戻るボタン-->
    <%= link_to "一覧へ戻る", redirect_before_url, class: "btn btn-sm btn-primary" %>

    <!-- フォローボタン -->
    <div class="col-md-8">
      <%= render 'follow_form' if logged_in? %>
    </div>







<%
=end
%>